asm-1462 added policies json validation
akeylesslabs/helm-charts pull request #10
Opened 2021-04-07 14:12 UTC by niv-ez

Added a Helm post-install pod for validating policies JSON structure (from values.yaml)

2021-04-08 07:46 UTC, liorhasson requested changes

2021-04-08 07:46 UTC, liorhasson commented on charts/akeyless-zero-trust-web-access/values.yaml
> -  enabled: false
revert

2021-04-08 08:03 UTC, niv-ez commented on charts/akeyless-zero-trust-web-access/values.yaml
> -  enabled: false
fixed

2021-04-11 13:14 UTC, liorhasson approved these changes

2021-04-11 13:15 UTC, merged