added allowedAccesses variable
akeylesslabs/helm-charts pull request #183
Opened 2023-06-04 07:32 UTC by avishay28

2023-06-04 13:56 UTC, OriBenHur-akeyless approved these changes

2023-06-05 07:51 UTC, niv-ez approved these changes

2023-06-05 14:33 UTC, OriBenHur-akeyless approved these changes

2023-06-05 16:10 UTC, renanaAkeyless requested changes
please make sure a new GW with this PR https://github.com/akeylesslabs/akeyless-main-repo/pull/3950 is released before merging

2023-06-05 21:17 UTC, OriBenHur-akeyless approved these changes

2023-06-11 08:18 UTC, avishay28 commented
@renanaAkeyless pleases remove the block.. gw changes already released

2023-06-11 08:28 UTC, merged